### ISSUE TITLE
Only email and Avatar are available

### ISSUE THREAD

**Issue by Javascipt** [sindresorhus/npm-user#9]
I think npm made some changes on the UI, now we can't get the `twitter`, `github`, `freenode` and `name`.  If there is no other way to get this information then the package might be deprecated.

**Comment by zeke** [comment]
I just brought this up with @seldo. 

The npm website is no longer displaying `twitter`, `github`, or `homepage` because they are attempting to thwart spam. Not sure how `github` and `twitter` handles could be used for spamming, but I think they just opted to remove all the profile data wholesale...

Apparently a new version of the npm website is in the works which will again display some of this info. Maybe not `homepage`, though.

**Comment by zeke** [comment]
New site appears to be live https://www.npmjs.com/~zeke

**Comment by Javascipt** [comment]
@zeke Thanks
